version: "3"
services:
# clickhouse cluster: 2shards x 1replica + 1keeper
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:24.10"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.10
    ports:
      - "9181:9181"
      - "9116:9116"
    volumes:
      - ./docker/clickhouse/keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml

  clickhouse01:
    image: "clickhouse/clickhouse-server:24.10"
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.11
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9117:9116"
    volumes:
      - ./docker/clickhouse/server01/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/server01/users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - clickhouse-keeper
    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
        interval: 30s
        timeout: 10s
        retries: 5

  clickhouse02:
    image: "clickhouse/clickhouse-server:24.10"
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.12
    ports:
      - "8124:8123"
      - "9001:9000"
      - "9118:9116"
    volumes:
      - ./docker/clickhouse/server02/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/server02/users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - clickhouse-keeper
    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
        interval: 30s
        timeout: 10s
        retries: 5

  clickhouse03:
    image: "clickhouse/clickhouse-server:24.10"
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.13
    ports:
      - "8125:8123"
      - "9003:9000"
      - "9119:9116"
    volumes:
      - ./docker/clickhouse/server03/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/server03/users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - clickhouse-keeper
    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
        interval: 30s
        timeout: 10s
        retries: 5

  clickhouse04:
    image: "clickhouse/clickhouse-server:24.10"
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.14
    ports:
      - "8126:8123"
      - "9004:9000"
      - "9120:9116"
    volumes:
      - ./docker/clickhouse/server04/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/server04/users.xml:/etc/clickhouse-server/users.xml
    depends_on:
      - clickhouse-keeper
    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  clickhouse-network:
    ipam:
      config:
        - subnet: 172.24.0.0/16